/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import java.awt.GridLayout;
import model.Aluno;
import model.Professor;
import model.Treino;
import dao.AlunoDAO;
import dao.ProfessorDAO;
import dao.TreinoDAO;
/**
 *
 * @author Roberto Augusto
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        alunoMenuItem = new javax.swing.JMenuItem();
        professorMenuItem = new javax.swing.JMenuItem();
        treinoMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroMenu.setText("Cadastro");

        alunoMenuItem.setText("Aluno");
        alunoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(alunoMenuItem);

        professorMenuItem.setText("Professor");
        professorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(professorMenuItem);

        treinoMenuItem.setText("Treino");
        treinoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(treinoMenuItem);

        jMenuBar1.add(cadastroMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoMenuItemActionPerformed
        // TODO add your handling code here:
        JTextField nomeTextField = new JTextField(15);
        JTextField dataNascimentoTextField = new JTextField(15);
        JTextField sexoTextField = new JTextField(15);
        JTextField telefoneTextField = new JTextField(15);
        JTextField emailTextField = new JTextField(15);
        
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeTextField);
        panel.add(new JLabel("Data Nascimento (yyyy-MM-dd):"));
        panel.add(dataNascimentoTextField);
        panel.add(new JLabel("Sexo (M/F):"));
        panel.add(sexoTextField);
        panel.add(new JLabel("Telefone:"));
        panel.add(telefoneTextField);
        panel.add(new JLabel("Email:"));
        panel.add(emailTextField);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Inserir Aluno",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        
        if(result == JOptionPane.OK_OPTION) {
            try {
                String nome = nomeTextField.getText();
                java.sql.Date dataNascimento = java.sql.Date.valueOf(dataNascimentoTextField.getText());
                char sexo = sexoTextField.getText().toUpperCase().charAt(0);
                String telefone = telefoneTextField.getText();
                String email = emailTextField.getText();
                java.sql.Date dataCadastro = new java.sql.Date(System.currentTimeMillis());
                
                AlunoDAO alunoDAO = new AlunoDAO();
                Aluno aluno = new Aluno(nome, dataNascimento, sexo, telefone, email, dataCadastro);

                if(alunoDAO.inserir(aluno)) {
                    JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao cadastrar aluno.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_alunoMenuItemActionPerformed

    private void professorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorMenuItemActionPerformed
        // TODO add your handling code here:
        JTextField nomeTextField = new JTextField(15);
        JTextField crefTextField = new JTextField(15);
        JTextField telefoneTextField = new JTextField(15);
        JTextField emailTextField = new JTextField(15);
        JRadioButton masculinoRadioButton = new JRadioButton("Masculino");
        JRadioButton femininoRadioButton = new JRadioButton("Feminino");
        
        ButtonGroup sexoButtonGroup = new ButtonGroup();
        sexoButtonGroup.add(masculinoRadioButton);
        sexoButtonGroup.add(femininoRadioButton);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeTextField);
        panel.add(new JLabel("Sexo:"));
        
        JPanel sexoPanel = new JPanel();
        sexoPanel.add(masculinoRadioButton);
        sexoPanel.add(femininoRadioButton);
        panel.add(sexoPanel);
        panel.add(new JLabel("CREF:"));
        panel.add(crefTextField);
        panel.add(new JLabel("Telefone:"));
        panel.add(telefoneTextField);
        panel.add(new JLabel("Email:"));
        panel.add(emailTextField);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Inserir Professor",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        
        if(result == JOptionPane.OK_OPTION) {
            try {
                String nome = nomeTextField.getText();
                char sexo;
                if (masculinoRadioButton.isSelected()) {
                    sexo = 'M';
                } else if (femininoRadioButton.isSelected()) {
                    sexo = 'F';
                } else {
                    JOptionPane.showMessageDialog(this, "Selecione o sexo.");
                    return;
                }
                String cref = crefTextField.getText();
                String telefone = telefoneTextField.getText();
                String email = emailTextField.getText();
                
                ProfessorDAO professorDAO = new ProfessorDAO();
                Professor professor = new Professor(nome, sexo, cref, telefone, email);

                if(professorDAO.inserir(professor)) {
                    JOptionPane.showMessageDialog(this, "Professor cadastrado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao cadastrar o professor.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_professorMenuItemActionPerformed

    private void treinoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinoMenuItemActionPerformed
        // TODO add your handling code here:
        JTextField nomeTextField = new JTextField(15);
        JTextField focoTreinoTextField = new JTextField(15);
        JTextField idAlunoTextField = new JTextField(15);
        JTextField idProfessorTextField = new JTextField(15);
        
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("ID do Aluno:"));
        panel.add(idAlunoTextField);
        panel.add(new JLabel("ID do Professor:"));
        panel.add(idProfessorTextField);
        panel.add(new JLabel("Nome do Treino:"));
        panel.add(nomeTextField);
        panel.add(new JLabel("Foco do Treino:"));
        panel.add(focoTreinoTextField);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Inserir Treino",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        
        if(result == JOptionPane.OK_OPTION) {
            try {
                int idAluno = Integer.parseInt(idAlunoTextField.getText());
                int idProfessor = Integer.parseInt(idProfessorTextField.getText());
                String nome = nomeTextField.getText();
                String focoTreino = focoTreinoTextField.getText();
                
                TreinoDAO treinoDAO = new TreinoDAO();
                Treino treino = new Treino(idAluno, idProfessor, nome, focoTreino);

                if(treinoDAO.inserir(treino)) {
                    JOptionPane.showMessageDialog(this, "Treino cadastrado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao cadastrar o treino.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_treinoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alunoMenuItem;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem professorMenuItem;
    private javax.swing.JMenuItem treinoMenuItem;
    // End of variables declaration//GEN-END:variables
}
