/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import java.awt.GridLayout;
import java.sql.Timestamp;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import model.Aluno;
import model.Professor;
import model.Treino;
import model.Equipamento;
import dao.AlunoDAO;
import dao.ProfessorDAO;
import dao.TreinoDAO;
import dao.EquipamentoDAO;
/**
 *
 * @author Roberto Augusto
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        alunoMenuItem = new javax.swing.JMenuItem();
        professorMenuItem = new javax.swing.JMenuItem();
        treinoMenuItem = new javax.swing.JMenuItem();
        equipamentoMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroMenu.setText("Cadastro");

        alunoMenuItem.setText("Aluno");
        alunoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(alunoMenuItem);

        professorMenuItem.setText("Professor");
        professorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(professorMenuItem);

        treinoMenuItem.setText("Treino");
        treinoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treinoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(treinoMenuItem);

        equipamentoMenuItem.setText("Equipamento");
        equipamentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipamentoMenuItemActionPerformed(evt);
            }
        });
        cadastroMenu.add(equipamentoMenuItem);

        jMenuBar1.add(cadastroMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoMenuItemActionPerformed
        // TODO add your handling code here:
        JTextField nomeTextField = new JTextField(15);
        JTextField emailTextField = new JTextField(15);
        JTextField pesoTextField = new JTextField(15);
        JTextField alturaTextField = new JTextField(15);
        JTextField sexoTextField = new JTextField(15);
        
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeTextField);
        panel.add(new JLabel("Email:"));
        panel.add(emailTextField);
        panel.add(new JLabel("Peso:"));
        panel.add(pesoTextField);
        panel.add(new JLabel("Altura:"));
        panel.add(alturaTextField);
        panel.add(new JLabel("Sexo:"));
        panel.add(sexoTextField);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Inserir Aluno",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        
        if(result == JOptionPane.OK_OPTION) {
            
            String nome = nomeTextField.getText();
            String email = emailTextField.getText();
            double peso = Double.parseDouble(pesoTextField.getText());
            double altura = Double.parseDouble(alturaTextField.getText());
            char sexo = sexoTextField.getText().charAt(0);
            
            AlunoDAO alunoDAO = new AlunoDAO();
            Aluno aluno = new Aluno(nome, email, peso, altura, sexo);

            if(alunoDAO.inserir(aluno)) {
                JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao cadastrar aluno.");
            }
        }
    }//GEN-LAST:event_alunoMenuItemActionPerformed

    private void professorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorMenuItemActionPerformed
        // TODO add your handling code here:
        JTextField nomeTextField = new JTextField(15);
        //JTextField sexoTextField = new JTextField(15);
        JRadioButton masculinoRadioButton = new JRadioButton("Masculino");
        JRadioButton femininoRadioButton = new JRadioButton("Feminino");
        
        ButtonGroup sexoButtonGroup = new ButtonGroup();
        sexoButtonGroup.add(masculinoRadioButton);
        sexoButtonGroup.add(femininoRadioButton);

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeTextField);
        panel.add(new JLabel("Sexo:"));
        
        JPanel sexoPanel = new JPanel();
        sexoPanel.add(masculinoRadioButton);
        sexoPanel.add(femininoRadioButton);
        panel.add(sexoPanel);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Inserir Professor",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        
        if(result == JOptionPane.OK_OPTION) {
            
            String nome = nomeTextField.getText();
            char sexo;
            if (masculinoRadioButton.isSelected()) {
                sexo = 'm';
            } else if (femininoRadioButton.isSelected()) {
                sexo = 'f';
            } else {
                JOptionPane.showMessageDialog(this, "Selecione o sexo.");
                return;
            }
            
            ProfessorDAO professorDAO = new ProfessorDAO();
            Professor professor = new Professor(nome, sexo);

            if(professorDAO.inserir(professor)) {
                JOptionPane.showMessageDialog(this, "Professor cadastrado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao cadastrar o professor.");
            }
        }
    }//GEN-LAST:event_professorMenuItemActionPerformed

    private void treinoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treinoMenuItemActionPerformed
        // TODO add your handling code here:
        JTextField nomeTextField = new JTextField(15);
        JTextField musculoTextField = new JTextField(15);
        JTextField horarioTextField = new JTextField(15);
        
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeTextField);
        panel.add(new JLabel("Músculo:"));
        panel.add(musculoTextField);
        panel.add(new JLabel("Horário (HH:mm):"));
        panel.add(horarioTextField);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Inserir Treino",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        
        if(result == JOptionPane.OK_OPTION) {
            
            String nome = nomeTextField.getText();
            String musculo = musculoTextField.getText();
            LocalTime horario = LocalTime.parse(horarioTextField.getText(), DateTimeFormatter.ofPattern("HH:mm"));
            
            TreinoDAO treinoDAO = new TreinoDAO();
            Treino treino = new Treino(nome, musculo, horario);

            if(treinoDAO.inserir(treino)) {
                JOptionPane.showMessageDialog(this, "Treino cadastrado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao cadastrar o treino.");
            }
        }
    }//GEN-LAST:event_treinoMenuItemActionPerformed

    private void equipamentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipamentoMenuItemActionPerformed
        // TODO add your handling code here:
        JTextField nomeTextField = new JTextField(15);
        
        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeTextField);
        
        int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Inserir Treino",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        
        if(result == JOptionPane.OK_OPTION) {
            
            String nome = nomeTextField.getText();
            
            EquipamentoDAO equipamentoDAO = new EquipamentoDAO();
            Equipamento equipamento = new Equipamento(nome);

            if(equipamentoDAO.inserir(equipamento)) {
                JOptionPane.showMessageDialog(this, "Equipamento cadastrado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao cadastrar o equipamento.");
            }
        }
    }//GEN-LAST:event_equipamentoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alunoMenuItem;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenuItem equipamentoMenuItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem professorMenuItem;
    private javax.swing.JMenuItem treinoMenuItem;
    // End of variables declaration//GEN-END:variables
}
